<a href="https://colab.research.google.com/github/ananyaravikumar548/Python-/blob/main/ANANYA_R_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a 2-dimensional NumPy array using np.array()
arr2= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print("Shape:", arr1.shape)
print("Number of dimensions:", arr1.ndim)
print("Data type:", arr1.dtype)
print("Size:", arr1.size)
print("Type:", type(arr1))


Shape: (10,)
Number of dimensions: 1
Data type: int64
Size: 10
Type: <class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array
print("Shape:", arr2.shape)
print("Number of dimensions:", arr2.ndim)
print("Data type:", arr2.dtype)
print("Size:", arr2.size)
print("Type:", type(arr2))


Shape: (3, 3)
Number of dimensions: 2
Data type: int64
Size: 9
Type: <class 'numpy.ndarray'>


In [6]:
# Attributes of 3-dimensional array
print("Shape:", arr3.shape)
print("Number of dimensions:", arr3.ndim)
print("Data type:", arr3.dtype)
print("Size:", arr3.size)
print("Type:", type(arr3))


Shape: (2, 2, 3)
Number of dimensions: 3
Data type: int64
Size: 12
Type: <class 'numpy.ndarray'>


In [7]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# Create an array of shape (7, 2, 3) of only zeros
arr =np.zeros ((7,2,3))
print (arr)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [9]:
# Create an array within a range of 0 and 100 with step 3
arr_range = np.arange(0, 100, 3)
print(arr_range)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
Arr1 = np.random.randint(0, 10, (7, 2))
print(Arr1)


[[7 9]
 [4 1]
 [9 7]
 [8 9]
 [0 6]
 [1 3]
 [5 6]]


In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
Arr2 = np.random.rand(3, 5)
print(Arr2)


[[0.57008962 0.18973755 0.90552743 0.83593235 0.60595471]
 [0.67029811 0.5762641  0.93323786 0.20780644 0.23971704]
 [0.79166504 0.12875906 0.1704287  0.58423885 0.86531816]]


In [16]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
Arr3 = np.random.randint(0, 10, (4, 6))
print(Arr3)


[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?
= the numbers are same beacuse we have set the seed to 42 hence numbers remain same

In [18]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

Arr4 = np.random.randint(1, 10, (3, 7))
print(Arr4)

# Find the unique numbers in the array you just created
unique_numbers = np.unique(Arr4)
print(unique_numbers)


[[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]
 [2 4 8 7 9 8 5]]
[1 2 3 4 5 6 7 8 9]


In [19]:
# Find the 0'th index of the latest array you created
index0 = Arr4[0]
print(index0)


[7 8 3 1 4 2 8]


In [20]:
# Get the first 2 rows of latest array you created
two_rows = Arr4[:2]
print(two_rows)


[[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]]


In [21]:
# Get the first 2 values of the first 2 rows of the latest array
two_values = two_rows[:, :2]
print(two_values)


[[7 8]
 [4 2]]


In [22]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_random = np.random.randint(0, 10, (3, 5))
arr_ones = np.ones((3, 5))

print("Random Array:\n", arr_random)
print("Array of Ones:\n", arr_ones)


Random Array:
 [[1 4 7 9 8]
 [8 0 8 6 8]
 [7 0 7 7 2]]
Array of Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
# Add the two arrays together
sum_arrays = arr_random + arr_ones
print(sum_arrays)


[[ 2.  5.  8. 10.  9.]
 [ 9.  1.  9.  7.  9.]
 [ 8.  1.  8.  8.  3.]]


In [24]:
# Create another array of ones of shape (5, 3)
array = np.ones((5, 3))
print(array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# Try add the array of ones and the other most recent array together
result = arr_random + array


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [26]:
result = arr_random + array.T
print(result)


[[ 2.  5.  8. 10.  9.]
 [ 9.  1.  9.  7.  9.]
 [ 8.  1.  8.  8.  3.]]


When you try the last cell, it produces an error. Why do think this is?
=It produces error beacuse the shape of the 2 arrays is different from each other so no compatability
How would you fix it?
=taking the transpose of the second array would make it possible

In [27]:
# Create another array of ones of shape (3, 5)
array1 = np.ones((3, 5))
print(array1)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# Subtract the new array of ones from the other most recent array
subtracted_array = arr_random - array1
print(subtracted_array)


[[ 0.  3.  6.  8.  7.]
 [ 7. -1.  7.  5.  7.]
 [ 6. -1.  6.  6.  1.]]


In [29]:
# Multiply the ones array with the latest array
multiplied_array = array1 * arr_random
print(multiplied_array)


[[1. 4. 7. 9. 8.]
 [8. 0. 8. 6. 8.]
 [7. 0. 7. 7. 2.]]


In [31]:
# Take the latest array to the power of 2 using '**'
squared_array = multiplied_array ** 2
print(squared_array)


[[ 1. 16. 49. 81. 64.]
 [64.  0. 64. 36. 64.]
 [49.  0. 49. 49.  4.]]


In [32]:
# Do the same thing with np.square()
squared_array_np = np.square(multiplied_array)
print(squared_array_np)


[[ 1. 16. 49. 81. 64.]
 [64.  0. 64. 36. 64.]
 [49.  0. 49. 49.  4.]]


In [33]:
# Find the mean of the latest array using np.mean()
mean_value = np.mean(squared_array)
print(mean_value)


39.333333333333336


In [34]:
# Find the maximum of the latest array using np.max()
max_value = np.max(squared_array)
print(max_value)


81.0


In [35]:
# Find the minimum of the latest array using np.min()
min_value = np.min(squared_array)
print(min_value)


0.0


In [36]:
# Find the standard deviation of the latest array
std_dev = np.std(squared_array)
print(std_dev)


26.97076606665488


In [37]:
# Find the variance of the latest array
variance = np.var(squared_array)
print(variance)


727.4222222222223


In [38]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = squared_array.reshape(3, 5, 1)
print(reshaped_array)


[[[ 1.]
  [16.]
  [49.]
  [81.]
  [64.]]

 [[64.]
  [ 0.]
  [64.]
  [36.]
  [64.]]

 [[49.]
  [ 0.]
  [49.]
  [49.]
  [ 4.]]]


In [39]:
# Transpose the latest array
transposed_array = reshaped_array.T
print(transposed_array)


[[[ 1. 64. 49.]
  [16.  0.  0.]
  [49. 64. 49.]
  [81. 36. 49.]
  [64. 64.  4.]]]


What does the transpose do? = tranpose here is used to interchange cloumns and rows

In [40]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
Array1 = np.random.randint(0, 11, (3, 3))
Array2 = np.random.randint(0, 11, (3, 2))

print(Array1)
print(Array2)


[[ 0  7  2]
 [ 2  0 10]
 [ 4  9  6]]
[[9 8]
 [6 8]
 [7 1]]


In [41]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(Array1, Array2)
print(dot_product)


[[ 56  58]
 [ 88  26]
 [132 110]]


In [42]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
Array3 = np.random.randint(0, 11, (4, 3))
Array4 = np.random.randint(0, 11, (4, 3))

print(Array3)
print(Array4)


[[ 0  6  6]
 [ 7  4  2]
 [ 7  5 10]
 [ 2  0  2]]
[[ 4  2  0]
 [ 4  9  6]
 [ 6 10  8]
 [ 9  9  2]]


In [43]:
# Perform a dot product on the two newest arrays you created
result = np.dot(Array3, Array4)  # Transposing Array4
print(result)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [44]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
result = np.dot(Array3, Array4.T)  # Transposing Array4
print(result)


[[ 12  90 108  66]
 [ 36  76  98 103]
 [ 38 133 172 128]
 [  8  20  28  22]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [46]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


array1 = np.random.randint(0, 11, (3, 3))
array2 = np.random.randint(0, 11, (3, 3))

print("Array 1:\n", array1)
print("Array 2:\n", array2)


Array 1:
 [[ 3 10  9]
 [ 6  8  6]
 [ 0  0  8]]
Array 2:
 [[10  8  3]
 [ 8  2  6]
 [ 5  7 10]]


In [47]:
# Compare the two arrays with '>'
comparison = array1 > array2
print(comparison)


[[False  True  True]
 [False  True False]
 [False False False]]


What happens when you compare the arrays with `>`? = it will result  in boolean either true or false with repsect to conditions

In [49]:
# Compare the two arrays with '>='
comparison1 = array1 >= array2
print(comparison1)


[[False  True  True]
 [False  True  True]
 [False False False]]


In [50]:
# Find which elements of the first array are greater than 7
greater_than_7 = array1 > 7
print(greater_than_7)


[[False  True  True]
 [False  True False]
 [False False  True]]


In [51]:
# Which parts of each array are equal? (try using '==')
equal_elements = array1 == array2
print(equal_elements)


[[False False False]
 [False False  True]
 [False False False]]


In [52]:
# Sort one of the arrays you just created in ascending order
sorted_array1 = np.sort(array1)
print(sorted_array1)


[[ 3  9 10]
 [ 6  6  8]
 [ 0  0  8]]


In [53]:
# Sort the indexes of one of the arrays you just created
sorted_indexes = np.argsort(array1)
print(sorted_indexes)


[[0 2 1]
 [0 2 1]
 [0 1 2]]


In [54]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(array1)
print(max_index)


1


In [55]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(array1)
print(min_index)


6


In [56]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_index_axis1 = np.argmax(array1, axis=1)
print(max_index_axis1)


[1 1 2]


In [57]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_index_axis0 = np.argmin(array1, axis=0)
print(min_index_axis0)


[2 2 1]


In [61]:
# Create an array of normally distributed random numbers
random_array = np.random.randn(3, 3)
print(random_array)


[[ 1.14282281  0.75193303  0.79103195]
 [-0.90938745  1.40279431 -1.40185106]
 [ 0.58685709  2.19045563 -0.99053633]]


In [62]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)
print(evenly_spaced_array)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

What happens when you try to broadcast A (3,) array with a (4,) array?

Explain why this operation might fail and how to fix it.



Broadcasting requires arrays to have compatible shapes of arrays
A (3,) array has 3 elements, while a (4,) array has 4 elements.
Since the dimensions do not match, NumPy shows error.
this can be solved by making both the array shapes compatibile

In [63]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6, 7])

arr1_resized = np.resize(arr1, (4,))
result = arr1_resized + arr2
print(result)


[5 7 9 8]


Write a NumPy program to add a 1D array of shape (3,) to a 2D array of shape (2, 3).


In [64]:


array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

result = array_2d + array_1d
print(result)


[[11 22 33]
 [14 25 36]]


Add a 1D array [10, 20, 30] to each row of a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9]].

In [65]:


array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_1d = np.array([10, 20, 30])

result = array_2d + array_1d
print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


Attempt to add a 1D array [10, 20] to a 2D array [[1, 2, 3], [4, 5, 6]]. Explain the error.

In [66]:


array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20])

result = array_2d + array_1d
print(result)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

ERROR = incompatility of shapes of two arrays while broadcasting

Multiply a 2D array [[1, 2], [3, 4]] with a 1D array [10, 20] using broadcasting.

In [67]:

arr2D = np.array([[1, 2], [3, 4]])
arr1D = np.array([10, 20])


result = arr2D * arr1D

print(result)


[[10 40]
 [30 80]]
